name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Debug environment
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Package.json content:"
          cat package.json

      - name: Install dependencies
        run: |
          npm install
          echo "Node modules after install:"
          ls -la node_modules/.bin | grep react-scripts

      - name: Build
        run: |
          export PATH="$PATH:$(pwd)/node_modules/.bin"
          echo "PATH: $PATH"
          which react-scripts || echo "react-scripts not found in PATH"
          npm run build
        env:
          CI: false

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUMORA_VENTURES }}"
          channelId: live
          projectId: lumora-ventures
