name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm ci
          # Explicitly install react-scripts if it's not being found
          npm install react-scripts --save-dev

      - name: Build React App
        run: |
          # Use npx to ensure react-scripts is found
          npx react-scripts --openssl-legacy-provider build
        env:
          CI: false

      - name: Install Functions Dependencies
        working-directory: ./functions
        run: npm ci

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUMORA_VENTURES }}"
          channelId: live
          projectId: lumora-ventures
